{
  "formatVersion": "1.1",
  "component": {
    "group": "de.genflux",
    "module": "nio",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "paherb2iubcvfptqnhkekjc5z4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nio-0.1.jar",
          "url": "nio-0.1.jar",
          "size": 45829,
          "sha512": "60ea94c041aa2f556c45b2328298dac7106cc4e9413ceb3121889d1c60876363b4d64a2ba1ab936e30964403d58c661b2691af4e15a39a10f0f4c13331417b77",
          "sha256": "179a39b835706ab8d13880555310452fe4e403853515e97b790a1e55f8590636",
          "sha1": "0f1730603b8854fcf8394b729656595e2e961d08",
          "md5": "f2b4725075f2b1c450d1ab1c0f211ed2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest-library",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "nio-0.1.jar",
          "url": "nio-0.1.jar",
          "size": 45829,
          "sha512": "60ea94c041aa2f556c45b2328298dac7106cc4e9413ceb3121889d1c60876363b4d64a2ba1ab936e30964403d58c661b2691af4e15a39a10f0f4c13331417b77",
          "sha256": "179a39b835706ab8d13880555310452fe4e403853515e97b790a1e55f8590636",
          "sha1": "0f1730603b8854fcf8394b729656595e2e961d08",
          "md5": "f2b4725075f2b1c450d1ab1c0f211ed2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nio-0.1-sources.jar",
          "url": "nio-0.1-sources.jar",
          "size": 37707,
          "sha512": "f8001d600d7e4983f52ba62045ca695c2af44cd16063e479669de9ed00c8df8d5242789d6cbc37a9226c4292c65cd2861f395e8a2d80493428429cb09b4f3405",
          "sha256": "89762d7e5200ba4094a238d8ba39cb2e5684a6b17896dff7b79033633990e2b6",
          "sha1": "fa98d68da12eec2a3b72bbcf5bfb436525f796be",
          "md5": "16d42c1200d1c1803ccbc7882227d89e"
        }
      ]
    }
  ]
}
