{
  "formatVersion": "1.1",
  "component": {
    "group": "de.genflux",
    "module": "nio",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "yygpk2kepff7dl2ag6qkljojii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nio-0.3.jar",
          "url": "nio-0.3.jar",
          "size": 59281,
          "sha512": "ce4b3c93fe144da8b1f20b63ddbb51b585ce45e07cf4d83320510bfd1c93464e5520e7e313d439344facc71e0156364738cf8a1415ff736ced587791b9498e21",
          "sha256": "fccc4b7fa9f8cb54dcd05b173b4fe1d299b09d4cb5390775eb1a602e7d59c135",
          "sha1": "7209a58e31d8b9eee97ec40c6edb0df2f86659b0",
          "md5": "f4cf5a3058744cd213e86d15e25c64fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest-library",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "nio-0.3.jar",
          "url": "nio-0.3.jar",
          "size": 59281,
          "sha512": "ce4b3c93fe144da8b1f20b63ddbb51b585ce45e07cf4d83320510bfd1c93464e5520e7e313d439344facc71e0156364738cf8a1415ff736ced587791b9498e21",
          "sha256": "fccc4b7fa9f8cb54dcd05b173b4fe1d299b09d4cb5390775eb1a602e7d59c135",
          "sha1": "7209a58e31d8b9eee97ec40c6edb0df2f86659b0",
          "md5": "f4cf5a3058744cd213e86d15e25c64fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nio-0.3-sources.jar",
          "url": "nio-0.3-sources.jar",
          "size": 56801,
          "sha512": "9aab812a8c807ee1fb10b4c9a10bf7076b5ae6be80ccb9d340858310dfd17fe8fd64d36ba9bac2e82d72438ca9209409007481a19383730a127e87dab341a443",
          "sha256": "d411a341325e6e583f32c505037845b95575d257a71146e43c8fbdad7b66c074",
          "sha1": "45e7b9d2f0e8e3d5ffa4db63b422f297b9c7c595",
          "md5": "52919c0b15dd67e38bbb7db22d713a72"
        }
      ]
    }
  ]
}
