{
  "formatVersion": "1.1",
  "component": {
    "group": "de.genflux",
    "module": "nio",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "v3daq4dpm5benisd6ehuce2aum"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nio-0.3.jar",
          "url": "nio-0.3.jar",
          "size": 46559,
          "sha512": "fd80c7e149b325034dbd792c0e49ce98380a3480bf317550300c6df6c592fc902e97653e9e2c81786f4a8482e5e3f538d89904ffc72059a5c1248ef5cdc954c2",
          "sha256": "18930e825166ed587b45bb068e7d3706757e7e082e95a9ef61a82ef2aac1d267",
          "sha1": "ee28cc96e48d615a2ce876f0193f5c074797f13e",
          "md5": "6ac8bce5b08d3d408e1db37fa1f2b9e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest-library",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "nio-0.3.jar",
          "url": "nio-0.3.jar",
          "size": 46559,
          "sha512": "fd80c7e149b325034dbd792c0e49ce98380a3480bf317550300c6df6c592fc902e97653e9e2c81786f4a8482e5e3f538d89904ffc72059a5c1248ef5cdc954c2",
          "sha256": "18930e825166ed587b45bb068e7d3706757e7e082e95a9ef61a82ef2aac1d267",
          "sha1": "ee28cc96e48d615a2ce876f0193f5c074797f13e",
          "md5": "6ac8bce5b08d3d408e1db37fa1f2b9e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nio-0.3-sources.jar",
          "url": "nio-0.3-sources.jar",
          "size": 38242,
          "sha512": "dac3d305afd6cf5d270eab0a0b72bfafc4c24f93d251d471e7b819988fc9ce9e9b0d50bb5b0d7cf4462700bd2f6ebafbd54bf901ae5119999ffc5ceb41abd451",
          "sha256": "bc1589e9cf5eadcccc26627398b1d2c3d7ec9ca3ce93d37999d18747e4ec70cb",
          "sha1": "1a97cc2d24de37f42317dc373d5a9041c91bceb4",
          "md5": "5d0fd07a73eceab3ee86443e87cce3ed"
        }
      ]
    }
  ]
}
